server:
  port:
    ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/currency_management
    username: ${SPRING_DATASOURCE_USERNAME:undefined}
    password: ${SPRING_DATASOURCE_PASSWORD:undefined}
  security:
    base-path: /currencyManagement/api/v1
    oauth2:
      keycloak:
        host: ${SPRING_SECURITY_OAUTH2_KEYCLOAK_HOST:undefined}
        port: ${SPRING_SECURITY_OAUTH2_KEYCLOAK_PORT:undefined}
        realm-name: ${SPRING_SECURITY_OAUTH2_KEYCLOAK_REALM_NAME:undefined}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

grpc:
  server:
    currency-service:
      port: ${GRPC_CURRENCY_SERVER_PORT:50051}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

springdoc:
  api-docs:
    path: /public/api/docs
  swagger-ui:
    path: /public/api/docs/swagger-ui.html
    operations-sorter: alpha