spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/currency_management
    username: ${SPRING_DATASOURCE_USERNAME:undefined}
    password: ${SPRING_DATASOURCE_PASSWORD:undefined}
  security:
    oauth2:
      keycloak:
        host: localhost
        port: 7080
        realm-name: moneyverse-fe
grpc:
  server:
    currency-service:
      port: 9080