server:
  port:
    ${PORT:8080}

spring:
  security:
    base-path: /currencyManagement/api/v1
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

springdoc:
  api-docs:
    path: /public/api/docs
  swagger-ui:
    path: /public/api/docs/swagger-ui.html
    operations-sorter: alpha