spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_management
    username: ${SPRING_DATASOURCE_USERNAME:undefined}
    password: ${SPRING_DATASOURCE_PASSWORD:undefined}
  security:
    oauth2:
      keycloak:
        host: localhost
        port: 7080
        realm-name: moneyverse-fe
        admin:
          client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:undefined}
          client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:undefined}
  kafka:
    admin:
      bootstrap-servers: localhost:29092
    consumer:
      group-id: user-management
grpc:
  server:
    user-service:
      port: 9081
  client:
    currency-service:
      host: localhost
      port: 9080