server:
  port:
    ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/user_management
    username: ${SPRING_DATASOURCE_USERNAME:undefined}
    password: ${SPRING_DATASOURCE_PASSWORD:undefined}
  security:
    base-path: /usersManagement/api/v1
    oauth2:
      keycloak:
        host: ${SPRING_SECURITY_OAUTH2_KEYCLOAK_HOST_HOST:undefined}
        port: ${SPRING_SECURITY_OAUTH2_KEYCLOAK_PORT:undefined}
        realm-name: ${SPRING_SECURITY_OAUTH2_KEYCLOAK_REALM_NAME:undefined}
        admin:
          client-id: ${SPRING_SECURITY_OAUTH2_KEYCLOAK_HOST_ADMIN_CLIENT_ID:undefined}
          client-secret: ${SPRING_SECURITY_OAUTH2_KEYCLOAK_HOST_ADMIN_CLIENT_SECRET:undefined}
  kafka:
    admin:
      bootstrap-servers: ${SPRING_KAFKA_ADMIN_BOOTSTRAP_SERVERS_HOST}:${SPRING_KAFKA_ADMIN_BOOTSTRAP_SERVERS_PORT}
    consumer:
      group-id: user-management

grpc:
  server:
    user-service:
      port: ${GRPC_USER_SERVER_PORT:50052}
  client:
    currency-service:
      host: ${SPRING_GRPC_CLIENT_CURRENCY_SERVICE_HOST:localhost}
      port: ${SPRING_GRPC_CLIENT_CURRENCY_SERVICE_PORT:50051}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

springdoc:
  api-docs:
    path: /public/api/docs
  swagger-ui:
    path: /public/api/docs/swagger-ui.html
    operations-sorter: alpha