version: "3"
services:
  krakend:
    image: krakend:2.10
    volumes:
      - .:/etc/krakend
    ports:
      - "8080:8080"
    environment:
      - FC_ENABLE=1
      - FC_SETTINGS=config/settings/demo
      - FC_PARTIALS=config/partials
      - FC_TEMPLATES=config/templates
      - FC_OUT=out/demo/out.json
      - SERVICE_NAME=KrakenD API Gateway
    command: [ "run", "-dc", "krakend.tmpl", "" ]