global:
  namespace: default
  environment: demo
  infisical:
    envSlug: dev
  dependencies:
    keycloak:
      port: 7080
      realm: "moneyverse-fe"
    postgresql:
      port: 5432
    clickhouse:
      port: 8123
    kafka:
      port: 9092
    redis:
      port: 6379
    currency_management:
      ports:
        http: 7001
      port: 50051
    user_management:
      ports:
        http: 7002
      port: 50052
    account_management:
      ports:
        http: 7003
      port: 50053
    budget_management:
      ports:
        http: 7004
      port: 50054
    transaction_management:
      ports:
        http: 7005
    analytics:
      ports:
        http: 7006
    krakend:
      ports:
        http: 8080
    nginx:
      ports:
        http: 80

infisical:
  authentification:
    clientId: "NTI1MTA2YjktM2JjOS00M2RlLWFmZWMtNWFlNjJhMDVkM2Iw"
    clientSecret: "ODU3ZDk1NDg2ZDg5YjYyNzRiMDY1NGRiZmZjOTNiZjViZGNhZmU5ZjI4YzI4ZjAwZWJiZTcxMTI1ZTUyNmM4ZA=="