apiVersion: v2
name: redis
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: "22.0.7"
    repository: https://charts.bitnami.com/bitnami
  - name: helm-library
    version: "0.1.0"
    repository: file://../helm-library