{{- include "helm-library.deployment" (list . "nginx.deployment") -}}

{{- define "nginx.deployment" -}}
spec:
  template:
    spec:
      initContainers:
        {{- include "wait-for-service" (dict "name" "account-management" "host" (include "moneyverse.account-management-host" .) "port" .Values.global.dependencies.account_management.ports.http) | nindent 8 }}
        {{- include "wait-for-service" (dict "name" "budget-management" "host" (include "moneyverse.budget-management-host" .) "port" .Values.global.dependencies.budget_management.ports.http) | nindent 8 }}
        {{- include "wait-for-service" (dict "name" "transaction-management" "host" (include "moneyverse.transaction-management-host" .) "port" .Values.global.dependencies.transaction_management.ports.http) | nindent 8 }}
{{- end -}}