{{- define "helm-library.secret.tpl" -}}
{{- $secret := .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name | default (printf "%s-secret" .Chart.Name ) | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
type: {{ $secret.type | default "Opaque" | quote }}
data: { }
{{- end }}
{{- define "helm-library.secret" -}}
{{- include "helm-library.util.merge" (append . "helm-library.secret.tpl") -}}
{{- end -}}