{{- define "helm-library.statefulset.tpl" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  serviceName: {{ .Chart.Name | quote }}
  selector:
    matchLabels:
      {{- include "helm-library.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-library.labels" . | nindent 8 }}
    spec:
      {{- if .Values.initContainer }}
      initContainers:
        - {{ include "helm-library.initContainer" (list . (printf "%s.initContainer" .Chart.Name )) }}
{{ include "helm-library.initContainer.tpl" . | indent 8 }}
      {{- end }}
      containers:
      {{- if .Values.container }}
        - {{ include "helm-library.container" (list . (printf "%s.container" .Chart.Name )) }}
      {{- else }}
        - {{- end }}
{{ include "helm-library.container.tpl" . | indent 8 }}
  {{- if .Values.volumeClaim }}
  volumeClaimTemplates:
    - {{ include "helm-library.volumeClaim" (list . (printf "%s.volumeClaim" .Chart.Name )) }}
  {{- end }}
{{ include "helm-library.volumeClaim.tpl" . | indent 8 }}
{{- end }}
{{- define "helm-library.statefulset" -}}
{{- include "helm-library.util.merge" (append . "helm-library.statefulset.tpl") -}}
{{- end -}}