spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analytics
    username: ${SPRING_DATASOURCE_USERNAME:undefined}
    password: ${SPRING_DATASOURCE_PASSWORD:undefined}
    clickhouse:
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      url: jdbc:clickhouse://localhost:8123/analytics
      username: ${SPRING_DATASOURCE_CLICKHOUSE_USERNAME:undefined}
      password: ${SPRING_DATASOURCE_CLICKHOUSE_PASSWORD:undefined}
  security:
    oauth2:
      keycloak:
        host: localhost
        port: 7080
        realm-name: moneyverse-fe
  kafka:
    admin:
      bootstrap-servers: localhost:29092
    consumer:
      group-id: dashboard