name: Account Management CI

on:
  push:
    branches:
      - master
      - feat/frontend
    paths:
      - 'moneyverse-be-bom/moneyverse-be-lib/moneyverse-account-management/**'
      - '.github/workflows/account-management-ci.yaml'
      - '.github/workflows/backend-ci.yaml'
  pull_request:
    paths:
      - 'moneyverse-be-bom/moneyverse-be-lib/moneyverse-account-management/**'
      - '.github/workflows/account-management-ci.yaml'
      - '.github/workflows/backend-ci.yaml'

jobs:
  account-management-be-job:
    uses: ./.github/workflows/backend-ci.yaml
    with:
      service: moneyverse-account-management
    secrets: inherit