name: Api Gateway CI

on:
  push:
    branches:
      - master
      - feat/frontend
    paths:
      - 'moneyverse-api-gateway/**'
      - '.github/workflows/api-gateway.yaml'
  pull_request:
    paths:
      - 'moneyverse-api-gateway/**'
      - '.github/workflows/api-gateway.yaml'

jobs:
  api-gateway-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Krakend image
        uses: docker/build-push-action@v6
        with:
          context: moneyverse-api-gateway/krakend
          file: moneyverse-api-gateway/krakend/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/moneyverse-krakend:latest