name: Frontend CI
on:
  push:
    branches:
      - master
      - feat/frontend
    paths:
      - 'moneyverse-fe/**'
      - '.github/workflows/frontend-ci.yaml'
  pull_request:
    paths:
      - 'moneyverse-fe/**'
      - '.github/workflows/frontend-ci.yaml'

jobs:
  frontend-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci
        working-directory: moneyverse-fe

      - name: Build
        run: npm run build
        working-directory: moneyverse-fe

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Angular image
        uses: docker/build-push-action@v6
        with:
          context: moneyverse-fe
          file: moneyverse-fe/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/moneyverse-fe:latest